// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Core.Entities;

[PrimaryKey("NHANVIEN_Id", "DeviceId")]
[Table("Account_Device_Mapping", Schema = "Pms")]
public partial class Account_Device_Mapping
{
    [Key]
    public Guid NHANVIEN_Id { get; set; }

    [Key]
    [StringLength(100)]
    public string DeviceId { get; set; }

    [StringLength(200)]
    public string DeviceName { get; set; }
}