// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Core.Entities;

[Table("AccountModel", Schema = "Pms")]
[Index("UserName", Name = "UserName_UNIQUE", IsUnique = true)]
public partial class AccountModel
{
    [Key]
    public Guid AccountId { get; set; }

    [StringLength(100)]
    public string UserName { get; set; }

    [StringLength(100)]
    public string Password { get; set; }

    [StringLength(10)]
    public string LastName { get; set; }

    [StringLength(50)]
    public string Phone { get; set; }

    [StringLength(500)]
    public string Email { get; set; }

    [StringLength(50)]
    public string Avatar { get; set; }

    public bool? IsCustomer { get; set; }

    public bool? IsViewSystem { get; set; }

    [StringLength(50)]
    public string PermissionViewData { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LastLogin { get; set; }

    public bool? Actived { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreateTime { get; set; }

    public Guid? CreateBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LastEditTime { get; set; }

    public Guid? LastEditBy { get; set; }

    public int? EmployeeCode { get; set; }

    [InverseProperty("Account")]
    public virtual ICollection<NotificationAccountMappingModel> NotificationAccountMappingModel { get; set; } = new List<NotificationAccountMappingModel>();

    [ForeignKey("AccountId")]
    [InverseProperty("Account")]
    public virtual ICollection<RolesModel> Roles { get; set; } = new List<RolesModel>();

    [ForeignKey("AccountId")]
    [InverseProperty("Account")]
    public virtual ICollection<StoreModel> Store { get; set; } = new List<StoreModel>();
}