// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Core.Entities;

[Keyless]
[Table("AddressModel", Schema = "Customer")]
public partial class AddressModel
{
    [StringLength(10)]
    public string AddressId { get; set; }

    public Guid? ProfileId { get; set; }

    [StringLength(500)]
    public string FirstName { get; set; }

    [StringLength(500)]
    public string LastName { get; set; }

    [StringLength(500)]
    public string CompanyName { get; set; }

    [StringLength(50)]
    public string Phone { get; set; }

    [StringLength(500)]
    public string Address { get; set; }

    public Guid? ProvinceId { get; set; }

    public Guid? DistrictId { get; set; }

    public Guid? WardId { get; set; }

    public bool? IsMain { get; set; }

    [StringLength(50)]
    public string TypeAddress { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreateTime { get; set; }

    public Guid? CreateBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LastEditTime { get; set; }

    public Guid? LastEditBy { get; set; }
}