// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Core.Entities;

[Table("BrandModel", Schema = "MasterData")]
public partial class BrandModel
{
    [Key]
    public Guid BrandId { get; set; }

    [StringLength(50)]
    public string BrandCode { get; set; }

    [StringLength(100)]
    public string BrandName { get; set; }

    public string ImageUrl { get; set; }
}