// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Core.Entities;

[Table("CatalogModel", Schema = "MasterData")]
public partial class CatalogModel
{
    [Key]
    public Guid CatalogId { get; set; }

    [StringLength(100)]
    public string CatalogTypeCode { get; set; }

    [StringLength(100)]
    public string CatalogCode { get; set; }

    public string CatalogText_vi { get; set; }

    public string CatalogText_en { get; set; }

    public string Note { get; set; }

    public int? OrderIndex { get; set; }

    public bool? Actived { get; set; }
}