// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Core.Entities;

[Table("EmployeeModel", Schema = "Pms")]
public partial class EmployeeModel
{
    [Key]
    public Guid EmployeeId { get; set; }

    public long EmployeeCode { get; set; }

    [StringLength(500)]
    public string FirstName { get; set; }

    [StringLength(500)]
    public string LastName { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreateTime { get; set; }

    public Guid? CreateBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LastEditTime { get; set; }

    public Guid? LastEditBy { get; set; }
}