// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Core.Entities;

[Table("FileAttachmentModel", Schema = "Customer")]
public partial class FileAttachmentModel
{
    [Key]
    public Guid FileAttachmentId { get; set; }

    public Guid ObjectId { get; set; }

    [Required]
    [StringLength(50)]
    public string FileAttachmentCode { get; set; }

    [StringLength(255)]
    public string FileAttachmentName { get; set; }

    [StringLength(50)]
    public string FileExtention { get; set; }

    [StringLength(500)]
    public string FileUrl { get; set; }

    public Guid? CreateBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreateTime { get; set; }

    public Guid? LastEditBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LastEditTime { get; set; }

    [StringLength(50)]
    public string FileType { get; set; }
}