// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Core.Entities;

[Table("FunctionModel", Schema = "Pms")]
public partial class FunctionModel
{
    [Key]
    [StringLength(50)]
    public string FunctionId { get; set; }

    [StringLength(50)]
    public string FunctionName { get; set; }

    [StringLength(500)]
    public string Notes { get; set; }

    [StringLength(50)]
    public string FunctionIcon { get; set; }

    public int? OrderIndex { get; set; }

    [InverseProperty("Function")]
    public virtual ICollection<PagePermissionModel> PagePermissionModel { get; set; } = new List<PagePermissionModel>();

    [ForeignKey("FunctionId")]
    [InverseProperty("Function")]
    public virtual ICollection<PageModel> Page { get; set; } = new List<PageModel>();
}