// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Core.Entities;

[Table("MenuModel", Schema = "Pms")]
public partial class MenuModel
{
    [Key]
    public Guid MenuId { get; set; }

    public Guid? MenuParentId { get; set; }

    [StringLength(100)]
    public string MenuName { get; set; }

    [StringLength(100)]
    public string Icon { get; set; }

    public int? OrderIndex { get; set; }

    [InverseProperty("Menu")]
    public virtual ICollection<PageModel> PageModel { get; set; } = new List<PageModel>();
}