// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Core.Entities;

[Table("NotificationModel", Schema = "utilities")]
public partial class NotificationModel
{
    [Key]
    public Guid NotificationId { get; set; }

    [StringLength(200)]
    public string NotificationUrl { get; set; }

    [StringLength(50)]
    public string SaleOrg { get; set; }

    [StringLength(400)]
    public string NotificationContent { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NotificationDateTime { get; set; }

    [InverseProperty("Notification")]
    public virtual ICollection<NotificationAccountMappingModel> NotificationAccountMappingModel { get; set; } = new List<NotificationAccountMappingModel>();
}