// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Core.Entities;

[Table("ProductAttributeModel", Schema = "MasterData")]
public partial class ProductAttributeModel
{
    [Key]
    public Guid ProductAttributeId { get; set; }

    [StringLength(50)]
    public string AttributeCode { get; set; }

    [StringLength(50)]
    public string CatalogCode { get; set; }

    [StringLength(500)]
    public string AttributeName { get; set; }

    public int? OrderIndex { get; set; }

    [StringLength(50)]
    public string Type { get; set; }

    public bool? Active { get; set; }
}