// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Core.Entities;

[Table("ProductModel", Schema = "Warehouse")]
public partial class ProductModel
{
    [Key]
    public Guid ProductId { get; set; }

    public int? ProductCode { get; set; }

    [StringLength(1000)]
    public string ProductName { get; set; }

    public Guid? CategoryId { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? Price { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? Quantity { get; set; }

    public string Descriptions { get; set; }

    public string Notes { get; set; }

    [StringLength(50)]
    public string Brand { get; set; }

    [StringLength(50)]
    public string SKU { get; set; }

    [Required]
    [StringLength(50)]
    public string UPC { get; set; }

    [StringLength(10)]
    public string MetaTitle { get; set; }

    public bool? IsGift { get; set; }

    public bool? IsMain { get; set; }

    public bool? IsInStock { get; set; }

    public bool? Active { get; set; }

    public string Image { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? PublishFrom { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? PublishUntil { get; set; }

    [StringLength(100)]
    public string PageUrl { get; set; }

    public bool? IsUseCodeForUrl { get; set; }

    [StringLength(100)]
    public string PageTitle { get; set; }

    public bool? IsUseCodeForTitle { get; set; }

    [StringLength(100)]
    public string MetaKeywords { get; set; }

    [StringLength(500)]
    public string MetaDescription { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreateTime { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LastEditTime { get; set; }

    public Guid? CreateBy { get; set; }

    public Guid? LastEditBy { get; set; }

    [ForeignKey("CategoryId")]
    [InverseProperty("ProductModel")]
    public virtual ProductCategoryModel Category { get; set; }
}