// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Core.Entities;

[Table("Product_Attribute_Mapping", Schema = "Warehouse")]
public partial class Product_Attribute_Mapping
{
    [Key]
    public Guid Id { get; set; }

    public Guid? ProductId { get; set; }

    [StringLength(50)]
    public string ProductAttributeCode { get; set; }

    [StringLength(50)]
    public string ParentCode { get; set; }
}