// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Core.Entities;

[Table("Product_Catalog_Mapping", Schema = "Warehouse")]
public partial class Product_Catalog_Mapping
{
    [Key]
    public Guid ProductTagId { get; set; }

    public Guid ProductId { get; set; }

    [Required]
    [StringLength(50)]
    public string CatalogCode { get; set; }

    [StringLength(50)]
    public string CatalogTypeCode { get; set; }
}