// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Core.Entities;

[Table("RefreshToken", Schema = "Pms")]
public partial class RefreshToken
{
    [Key]
    public int Id { get; set; }

    public string Token { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? Expires { get; set; }

    public bool? IsExpired { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? Created { get; set; }

    [StringLength(50)]
    public string CreatedByIP { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? Revoked { get; set; }

    [StringLength(50)]
    public string RevokedByIP { get; set; }

    public string ReplacedByToken { get; set; }

    public bool? IsActive { get; set; }
}