// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Core.Entities;

[Table("RolesModel", Schema = "Pms")]
public partial class RolesModel
{
    [Key]
    public Guid RolesId { get; set; }

    [StringLength(50)]
    public string RolesCode { get; set; }

    [StringLength(50)]
    public string RolesName { get; set; }

    public bool? Actived { get; set; }

    public int? OrderIndex { get; set; }

    public bool? IsSystem { get; set; }

    public bool? IsEmployeeGroup { get; set; }

    [InverseProperty("Roles")]
    public virtual ICollection<PagePermissionModel> PagePermissionModel { get; set; } = new List<PagePermissionModel>();

    [ForeignKey("RolesId")]
    [InverseProperty("Roles")]
    public virtual ICollection<AccountModel> Account { get; set; } = new List<AccountModel>();
}