// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Core.Entities;

[Table("StoreModel", Schema = "MasterData")]
public partial class StoreModel
{
    [Key]
    public Guid StoreId { get; set; }

    [StringLength(50)]
    public string StoreCode { get; set; }

    public Guid? StoreTypeId { get; set; }

    [StringLength(100)]
    public string StoreName { get; set; }

    public Guid? CompanyId { get; set; }

    [StringLength(100)]
    public string TelProduct { get; set; }

    [StringLength(100)]
    public string TelService { get; set; }

    [StringLength(500)]
    public string Address { get; set; }

    public Guid? ProvinceId { get; set; }

    public Guid? DistrictId { get; set; }

    public Guid? WardId { get; set; }

    [StringLength(100)]
    public string Fax { get; set; }

    [StringLength(1000)]
    public string LogoUrl { get; set; }

    [StringLength(1000)]
    public string ImageUrl { get; set; }

    public int? OrderIndex { get; set; }

    public bool Actived { get; set; }

    [StringLength(50)]
    public string mLat { get; set; }

    [StringLength(50)]
    public string mLong { get; set; }

    public TimeSpan? StartTimeWorking { get; set; }

    public TimeSpan? EndTimeWorking { get; set; }

    [ForeignKey("CompanyId")]
    [InverseProperty("StoreModel")]
    public virtual CompanyModel Company { get; set; }

    [ForeignKey("StoreId")]
    [InverseProperty("Store")]
    public virtual ICollection<AccountModel> Account { get; set; } = new List<AccountModel>();
}